# Generated by Django 5.0.1 on 2024-03-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('local', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=2000)),
                ('venue', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='videoLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistName', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('embedLink', models.CharField(max_length=500)),
            ],
        ),
    ]
