# Generated by Django 5.0.1 on 2024-03-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressKit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='ticket_link',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
