# Generated by Django 5.0.1 on 2024-01-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressKit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='venue',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shows',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
