# Generated by Django 5.0.1 on 2024-03-19 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressKit', '0003_sociallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='artistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='artistChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pressKit.artistinfo'),
        ),
        migrations.AddField(
            model_name='videolinks',
            name='artistChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pressKit.artistinfo'),
        ),
    ]
