# Generated by Django 5.0.1 on 2024-03-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressKit', '0004_artistinfo_sociallinks_artistchoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinks',
            name='artistName',
        ),
        migrations.RemoveField(
            model_name='videolinks',
            name='artistName',
        ),
    ]
